### ISSUE TITLE
Duplicated provisioner

### ISSUE THREAD

**Issue by pierreyves-lebrun** [eaksel/packer-Win2019#1]
Is there a reason for win2019-gui_uefi.json to call win-update.ps1 script twice?

```
      {
        "type": "powershell",
        "scripts": ["scripts/win-update.ps1"]
      },
      {
        "type": "windows-restart",
        "restart_timeout": "30m"
      },
      {
        "type": "powershell",
        "scripts": ["scripts/win-update.ps1"]
      },
      {
        "type": "windows-restart",
        "restart_timeout": "30m"
      }
```

Thanks otherwise for this repo!

**Comment by eaksel** [comment]
Hello @pierreyves-lebrun,

The reason for having the provisioner twice is because the windows update process needs 2 passes with a reboot in between to install all the available updates.

Here's a screenshot of the update process:

![update_provisioner](https://user-images.githubusercontent.com/28254097/73173771-6b0f5e80-4106-11ea-90b6-96b9a40f9def.png)

You're welcome.

**Comment by pierreyves-lebrun** [comment]
Makes sense, thanks!
